# Generated by Django 6.0.1 on 2026-02-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiclespecstemplate',
            name='core_vehicl_model_6e72ea_idx',
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='specs_template',
            field=models.ForeignKey(blank=True, help_text='Master template for this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_info', to='core.vehiclespecstemplate'),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='custom_battery_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='custom_motor_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='custom_range_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='custom_top_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='customization_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='specs_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_instances', to='core.vehiclespecstemplate'),
        ),
        migrations.AlterField(
            model_name='vehiclespecs',
            name='vin',
            field=models.OneToOneField(help_text='Vehicle Identification Number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='individual_specs', serialize=False, to='core.vehicleinfo'),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='abs_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='acceleration_0_to_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='battery_capacity',
            field=models.IntegerField(help_text='Battery capacity in Wh'),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='battery_cells_config',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='boot_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='charging_time_0_to_100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='charging_time_0_to_80',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='cruise_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='fast_charging_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='front_brake_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='ground_clearance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='motor_power',
            field=models.IntegerField(help_text='Motor power in Watts'),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='motor_torque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='motor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='payload_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='range_city',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='range_highway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='rear_brake_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='regenerative_braking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='reverse_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='seating_capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='suspension_front',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='suspension_rear',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='tire_size_front',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='tire_size_rear',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='wheelbase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclespecstemplate',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
