# Generated by Django 6.0.1 on 2026-02-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vehiclespecstemplate_core_vehicl_model_6e72ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerawdata',
            name='vcu_id',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
