# Generated by Django 6.0.1 on 2026-02-06 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehiclerawdata_vcu_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-time'], 'verbose_name': 'Access Log', 'verbose_name_plural': 'Access Logs'},
        ),
        migrations.AlterModelOptions(
            name='vehiclerawdata',
            options={'ordering': ['-time'], 'verbose_name_plural': 'Vehicle Raw Data'},
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='vehiclerawdata',
            old_name='satellites',
            new_name='satatellites',
        ),
        migrations.RemoveField(
            model_name='vehiclerawdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='vehiclerawdata',
            name='time',
            field=models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now),
        ),
    ]
