# Generated by Django 6.0.1 on 2026-02-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_accesslog_options_alter_vehiclerawdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerawdata',
            old_name='satatellites',
            new_name='satellites',
        ),
    ]
