# Generated by Django 6.0.1 on 2026-02-09 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_satatellites_vehiclerawdata_satellites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=50, unique=True, verbose_name='Reference No.')),
                ('dealer_code', models.CharField(max_length=50, unique=True, verbose_name='Dealer Code')),
                ('dealership_name', models.CharField(max_length=255, verbose_name='Dealership Name')),
                ('for_party_creation', models.CharField(max_length=255, verbose_name='FOR PARTY CREATION')),
                ('dealer_address', models.TextField(verbose_name="Dealer's Address")),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('pin_code', models.CharField(max_length=10, verbose_name='Pin Code')),
                ('gst_no', models.CharField(max_length=15, verbose_name='GST No.')),
                ('loi_date', models.DateField(blank=True, null=True, verbose_name='LOI Date')),
                ('loi_valid_upto', models.DateField(blank=True, null=True, verbose_name='LOI Valid Upto')),
                ('lead_status', models.CharField(max_length=100, verbose_name='Lead status Digital/Newspaper/scouting')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to the authentication user table', on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Information',
                'verbose_name_plural': 'Dealer Information',
            },
        ),
    ]
