# Generated by Django 6.0.1 on 2026-02-09 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dealerinformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealervehicle',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dealer_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='sales_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='sales_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OEM', 'OEM / Plant User'), ('SALES', 'Sales Manager'), ('RND', 'R&D User'), ('DEALER', 'Dealer'), ('SERVICE', 'Service Engineer'), ('FLEET', 'Fleet Manager'), ('USER', 'End User')], default='USER', max_length=20),
        ),
    ]
