# Generated by Django 6.0.1 on 2026-02-10 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fleet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TyrePressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('vcu_id', models.CharField(db_index=True, max_length=100)),
                ('vin', models.CharField(db_index=True, max_length=50)),
                ('front_pressure', models.IntegerField(default=0, help_text='Front tyre pressure in PSI')),
                ('rear_pressure', models.IntegerField(default=0, help_text='Rear tyre pressure in PSI')),
                ('device_timestamp', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tyre Pressure',
                'verbose_name_plural': 'Tyre Pressures',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['vcu_id', '-time'], name='core_tyrepr_vcu_id_af6e5c_idx'), models.Index(fields=['vin', '-time'], name='core_tyrepr_vin_1a594f_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('vcu_id', models.CharField(db_index=True, max_length=100)),
                ('vin', models.CharField(db_index=True, max_length=50)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0, help_text='Altitude in meters')),
                ('speed', models.FloatField(default=0.0, help_text='GPS speed in km/h')),
                ('satellites', models.IntegerField(default=0, help_text='Number of satellites')),
                ('hdop', models.FloatField(default=0.0, help_text='Horizontal dilution of precision')),
                ('device_timestamp', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vehicle Location',
                'verbose_name_plural': 'Vehicle Locations',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['vcu_id', '-time'], name='core_vehicl_vcu_id_05e3a5_idx'), models.Index(fields=['vin', '-time'], name='core_vehicl_vin_3d7ba2_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('vcu_id', models.CharField(db_index=True, max_length=100)),
                ('vin', models.CharField(db_index=True, max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('firmware_version', models.CharField(default='', max_length=20)),
                ('rssi', models.IntegerField(default=0, help_text='WiFi signal strength in dBm')),
                ('uptime', models.BigIntegerField(default=0, help_text='Uptime in seconds')),
                ('heap_free', models.IntegerField(default=0, help_text='Free heap in bytes')),
                ('packets_received', models.IntegerField(default=0)),
                ('packets_published', models.IntegerField(default=0)),
                ('reconnect_count', models.IntegerField(default=0)),
                ('device_timestamp', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vehicle Status',
                'verbose_name_plural': 'Vehicle Statuses',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['vcu_id', '-time'], name='core_vehicl_vcu_id_002b62_idx'), models.Index(fields=['vin', '-time'], name='core_vehicl_vin_3bccdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcu_id', models.CharField(db_index=True, max_length=100)),
                ('vin', models.CharField(db_index=True, max_length=50)),
                ('alert_type', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, help_text='Additional alert data', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vcu_id', 'status', '-created_at'], name='core_alert_vcu_id_02c532_idx'), models.Index(fields=['vin', 'status', '-created_at'], name='core_alert_vin_7a6fad_idx'), models.Index(fields=['severity', 'status'], name='core_alert_severit_ad8a8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcu_id', models.CharField(db_index=True, max_length=100)),
                ('vin', models.CharField(db_index=True, max_length=50)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('start_odometer', models.FloatField(default=0.0)),
                ('end_odometer', models.FloatField(default=0.0)),
                ('start_soc', models.FloatField(default=0.0)),
                ('end_soc', models.FloatField(default=0.0)),
                ('energy_consumed_wh', models.FloatField(default=0.0)),
                ('max_speed_kmh', models.IntegerField(default=0)),
                ('avg_speed_kmh', models.FloatField(default=0.0)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('eco_score', models.IntegerField(default=0, help_text='0-100 driving efficiency score')),
                ('co2_saved_kg', models.FloatField(default=0.0)),
                ('efficiency_wh_km', models.FloatField(default=0.0)),
                ('route', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['vcu_id', '-start_time'], name='core_trip_vcu_id_fd4b6c_idx'), models.Index(fields=['vin', '-start_time'], name='core_trip_vin_9b8d3f_idx'), models.Index(fields=['is_active'], name='core_trip_is_acti_714c06_idx')],
            },
        ),
    ]
