# Generated by Django 6.0.1 on 2026-02-11 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tyrepressure_vehiclelocation_vehiclestatus_alert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcu_id', models.CharField(db_index=True, max_length=50)),
                ('command', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_command_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vcu_id', '-created_at'], name='control_com_vcu_id_b6b193_idx'), models.Index(fields=['status', '-created_at'], name='control_com_status_73262d_idx')],
            },
        ),
    ]
