# Generated by Django 6.0.1 on 2026-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_controlcommandlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerawdata',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='vehiclerawdata',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehiclerawdata',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehiclerawdata',
            name='satellites',
        ),
        migrations.AddIndex(
            model_name='vehiclerawdata',
            index=models.Index(fields=['vcu_id', '-time'], name='core_vehicl_vcu_id_4e93fe_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerawdata',
            index=models.Index(fields=['vin', '-time'], name='core_vehicl_vin_bd1cd7_idx'),
        ),
    ]
