# Generated by Django 6.0.1 on 2026-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_vehiclerawdata_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcu_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('power', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('horn', models.BooleanField(default=False)),
                ('headlights', models.BooleanField(default=False)),
                ('hazard', models.BooleanField(default=False)),
                ('immobilizer', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw_state', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle State',
                'verbose_name_plural': 'Vehicle States',
                'db_table': 'vehicle_state',
            },
        ),
    ]
